### ISSUE TITLE
Error Types Typeorm@0.2.30

### ISSUE THREAD

**Issue by reaink** [freshgiammi-lab/connect-typeorm#23]
Types of parameters 'selection' and 'selection' are incompatible.
                                                                        Type 'string' is not assignable to type '(qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>'

**Comment by nykula** [comment]
Hello, thanks for your report. Can you please provide a code example where the error happens? I've been trying to get this error with connect-typeorm 1.1.4 and various typeorm versions today, including 0.2.30, but I haven't received it. None of the literals `SelectQueryBuilder`, `qb`, `selection` are present in the connect-typeorm codebase.
