### ISSUE TITLE
Maintainership of connect-typeorm

### ISSUE THREAD

**Issue by nykula** [freshgiammi-lab/connect-typeorm#28]
@0x0ece @Kehrlann @jdhuntington

Hello. I appreciate your contributions to connect-typeorm. The library has helped many people for over three years.

Where I work now, Node.js isn't a primary tool, and I no longer dogfood this library. I have recurring health issues and spend most of my free time far from a computer.

It'd be great if any of you whom I mentioned above could take over the v2 release and further maintenance of connect-typeorm. Please reply and I'll be happy to send you repository and npm access.

**Comment by jdhuntington** [comment]
The other folks on this thread certainly have more experience with this codebase than I do, but I'm more than happy to help with ongoing maintenance. Also, thank you @nykula for this project! It's been a tremendous help.

**Comment by 0x0ece** [comment]
Sorry to hear about the health issues @nykula, I wish you to resolve them.

Definitely happy to help too, we actively use typeorm-connect and want to make sure it's stable and kept up to date.

Let's wait to hear from @Kehrlann then maybe we can have a quick chat "in person" to say hi?

**Comment by Kehrlann** [comment]
Hi @nykula! It's been a pleasure contributing. Unfortunately I did use `connect-typeorm` on customer projects, but don't use it anymore - I'm not even using node. I may chime in here and there but I feel the other may be better candidates.

I hope your health gets better. Take good care, thanks for reaching out <3

**Comment by nykula** [comment]
@0x0ece and @jdhuntington
Great! I have sent the invites. What platform and hours would be comfortable for the chat? My time zone is UTC+3.

@Kehrlann 
Alright, glad to hear from you and thanks for your good wishes.

**Comment by 0x0ece** [comment]
I'm in CET right now - if you'd like we have a [discord server](https://discord.gg/cbWW8akyW9) that we can use to discuss more privately.

**Comment by 0x0ece** [comment]
@jdhuntington, @nykula any update?

**Comment by 0x0ece** [comment]
hey @nykula, jdhuntington and I are on the discord server, does that work for you?

**Comment by freshgiammi** [comment]
Hi @jdhuntington and @0x0ece, I've taken over for maintenance. 
Please feel free to ping me if you guys ever wanna get aboard,
