### ISSUE TITLE
Session `expiredAt` field is always updated in store (even if `resave` option set to false)

### ISSUE THREAD

**Issue by yatarkan** [freshgiammi-lab/connect-typeorm#31]
Is it expected behaviour that `expiredAt` field is always updated in store if session configuration includes `resave` option set to `false`?
As far as I see it is triggered from `touch` method (https://github.com/nykula/connect-typeorm/blob/master/src/app/TypeormStore/TypeormStore.ts#L199). 

I have looked at other implementations of session store (e.g. [connect-mongo](https://github.com/jdesboeufs/connect-mongo)) and there `expires` is not changed if session cookie already has expiration date ([place in sources](https://github.com/jdesboeufs/connect-mongo/blob/master/src/lib/MongoStore.ts#L434)).

**Comment by freshgiammi** [comment]
Merged.
