### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by qiuzuhui** [freshgiammi-lab/connect-typeorm#35]
Seems this project didn't update for one year, i used it in some project , but currently has compatibility issue with typeorm.

**Comment by SimonCockx** [comment]
I want to implement session management in my NestJS + TypeORM application, and this package would help a lot with that. A shame to see this project abandoned. :/

**Comment by freshgiammi** [comment]
I came to the same conclusion given that the project hasn't been updated for a while. I've been using this package for a while at my company, but we've switched do TypeORM v0.3 and it doesn't play nice anymore, so I had to fork and maintain it separately. 
It currently lives here https://github.com/freshgiammi/connect-typeorm (but I've also made it publicly available via [NPM](https://www.npmjs.com/package/@freshgiammi/connect-typeorm)).

If @nykula wants, I'm more than happy to handle this project personally!

**Comment by nykula** [comment]
@freshgiammi
Hello. The commits in your fork look good. I sent you an npm invitation. If you set up a github organization for the project and invite me, I will transfer the repository there and leave. I am sorry that I keep letting the users down, including the nice people from previous discussions who tried to pick up the development. Please contact them if you can. I never did, I have been stuck in some very stressful personal experience.

---

To anyone passing by:
**Death to the Russian empire.**

**Comment by freshgiammi** [comment]
Hi, I've accepted your invitation. I believe you should be able to transfer the whole repository directly to my account without needing to set up an organization, but I can set one up if you think that's a better way. As for the other people you've mentioned, I'm pinging @jdhuntington and @0x0ece from #28, which I believe are the ones you're talking about.

Please do not apologise, I completely understand what you're talking about: I see you're from Kyiv and you have no responsibility for what happened. I hope this message finds you well and I hope you and your loved ones can keep staying safe for as long as this situation goes on, which I pray is as little as possible. ❤️

**Comment by nykula** [comment]
User transfer does not work when you have a fork. I can link your fork in the description and archive the repository, but transferring to an organization with an automatic redirect seems cleaner.

**Comment by freshgiammi** [comment]
Yeah, that makes sense. I've created an organization (https://github.com/freshgiammi-lab) and invited you to join. Feel free to make the transfer whenever you want, I probably won't be able to realign my fork/commits and update the package on NPM until this weekend.

**Comment by nykula** [comment]
Thank you! :heart: Done the transfer.

**Comment by freshgiammi** [comment]
Thanks, I've now re-alligned branches and published v2.0.0 to NPM. 

Please take care. ❤️
